ALTER TABLE "metadata_descendant" ALTER COLUMN "descendant_name" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_descendant" ALTER COLUMN "descendant_image_url" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_descendant_skill" ALTER COLUMN "skill_type" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_descendant_skill" ALTER COLUMN "skill_name" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_descendant_skill" ALTER COLUMN "element_type" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_descendant_skill" ALTER COLUMN "arche_type" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_descendant_skill" ALTER COLUMN "skill_image_url" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_descendant_skill" ALTER COLUMN "skill_description" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_descendant_skill" ALTER COLUMN "metadata_descendant_descendant_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_descendant_stat" ALTER COLUMN "metadata_descendant_descendant_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_descendant_stat" ALTER COLUMN "level" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_descendant_stat_stat_detail" ALTER COLUMN "stat_type" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_descendant_stat_stat_detail" ALTER COLUMN "stat_value" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_descendant_stat_stat_detail" ALTER COLUMN "metadata_descendant_stat_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_external_component" ALTER COLUMN "external_component_name" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_external_component" ALTER COLUMN "image_url" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_external_component" ALTER COLUMN "external_component_equipment_type" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_external_component" ALTER COLUMN "external_component_tier" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_external_component_base_stat" ALTER COLUMN "metadata_external_component_external_component_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_external_component_base_stat" ALTER COLUMN "level" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_external_component_base_stat" ALTER COLUMN "stat_value" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_external_component_set_option_detail" ALTER COLUMN "metadata_external_component_external_component_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_external_component_set_option_detail" ALTER COLUMN "set_option" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_external_component_set_option_detail" ALTER COLUMN "set_count" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_external_component_set_option_detail" ALTER COLUMN "set_option_effect" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_module" ALTER COLUMN "module_name" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_module" ALTER COLUMN "image_url" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_module" ALTER COLUMN "module_type" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_module" ALTER COLUMN "module_tier" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_module" ALTER COLUMN "module_socket_type" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_module" ALTER COLUMN "module_class" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_module_stat" ALTER COLUMN "metadata_module_module_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_module_stat" ALTER COLUMN "level" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_module_stat" ALTER COLUMN "module_capacity" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_module_stat" ALTER COLUMN "value" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_reactor" ALTER COLUMN "reactor_name" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_reactor" ALTER COLUMN "image_url" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_reactor" ALTER COLUMN "reactor_tier" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_reactor" ALTER COLUMN "optimized_condition_type" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_reactor_skill_power" ALTER COLUMN "metadata_reactor_reactor_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_reactor_skill_power" ALTER COLUMN "level" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_reactor_skill_power" ALTER COLUMN "skill_atk_power" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_reactor_skill_power" ALTER COLUMN "sub_skill_atk_power" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_reactor_skill_power_enchant_effect" ALTER COLUMN "metadata_reactor_skill_power_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_reactor_skill_power_enchant_effect" ALTER COLUMN "stat_type" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_reactor_skill_power_enchant_effect" ALTER COLUMN "value" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_reactor_skill_power_skill_power_coefficient" ALTER COLUMN "metadata_reactor_skill_power_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_reactor_skill_power_skill_power_coefficient" ALTER COLUMN "coefficient_stat_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_reactor_skill_power_skill_power_coefficient" ALTER COLUMN "coefficient_stat_value" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_reward" ALTER COLUMN "map_name" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_reward_battle_zone" ALTER COLUMN "battle_zone_name" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_reward_battle_zone" ALTER COLUMN "metadata_reward_map_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_reward_battle_zone_reward" ALTER COLUMN "metadata_reward_battle_zone_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_reward_battle_zone_reward" ALTER COLUMN "rotation" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_reward_battle_zone_reward" ALTER COLUMN "reward_type" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_reward_battle_zone_reward" ALTER COLUMN "reactor_element_type" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_reward_battle_zone_reward" ALTER COLUMN "weapon_rounds_type" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_reward_battle_zone_reward" ALTER COLUMN "arche_type" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_stat" ALTER COLUMN "stat_name" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_title" ALTER COLUMN "title_name" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_void_battle" ALTER COLUMN "void_battle_name" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_weapon" ALTER COLUMN "weapon_name" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_weapon" ALTER COLUMN "image_url" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_weapon" ALTER COLUMN "weapon_type" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_weapon" ALTER COLUMN "weapon_tier" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_weapon" ALTER COLUMN "weapon_rounds_type" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_weapon" ALTER COLUMN "weapon_perk_ability_name" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_weapon" ALTER COLUMN "weapon_perk_ability_description" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_weapon" ALTER COLUMN "weapon_perk_ability_image_url" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_weapon_base_stat" ALTER COLUMN "metadata_weapon_weapon_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_weapon_base_stat" ALTER COLUMN "stat_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_weapon_base_stat" ALTER COLUMN "stat_value" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_weapon_firearm_atk" ALTER COLUMN "level" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_weapon_firearm_atk" ALTER COLUMN "metadata_weapon_weapon_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_weapon_firearm_atk_firearm" ALTER COLUMN "metadata_weapon_firearm_atk_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_weapon_firearm_atk_firearm" ALTER COLUMN "firearm_atk_type" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "metadata_weapon_firearm_atk_firearm" ALTER COLUMN "firearm_atk_value" DROP NOT NULL;